/**
 * generate-config.js
 * ------------------
 * Runs at Vercel build time (or locally via: node generate-config.js).
 * Reads environment variables and writes config.js so the static site
 * never has secrets hardcoded in the source repository.
 *
 * Set these in: Vercel Dashboard → Project → Settings → Environment Variables
 */

const fs   = require('fs');
const path = require('path');

// ── Read from environment (Vercel injects these at build time) ──
const config = {
  OPENROUTER_API_KEY : process.env.OPENROUTER_API_KEY || '',
  OPENROUTER_MODEL   : process.env.OPENROUTER_MODEL   || 'openai/gpt-oss-120b:free',
  WHATSAPP_NUMBER    : process.env.WHATSAPP_NUMBER    || '',
  CALENDLY_URL       : process.env.CALENDLY_URL       || '',
};

// ── Warn if any required key is missing ─────────────────────────
const required = ['OPENROUTER_API_KEY', 'WHATSAPP_NUMBER', 'CALENDLY_URL'];
required.forEach(key => {
  if (!config[key]) {
    console.warn(`⚠️  Warning: Environment variable "${key}" is not set.`);
  }
});

// ── Generate config.js content ───────────────────────────────────
const output = `/* ============================================================
   AUTO-GENERATED by generate-config.js — DO NOT EDIT MANUALLY
   Generated at: ${new Date().toISOString()}
   ============================================================ */

window.SITE_CONFIG = {
  OPENROUTER_API_KEY : ${JSON.stringify(config.OPENROUTER_API_KEY)},
  OPENROUTER_MODEL   : ${JSON.stringify(config.OPENROUTER_MODEL)},
  WHATSAPP_NUMBER    : ${JSON.stringify(config.WHATSAPP_NUMBER)},
  CALENDLY_URL       : ${JSON.stringify(config.CALENDLY_URL)},
};
`;

// ── Write to config.js ───────────────────────────────────────────
const outputPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outputPath, output, 'utf8');

console.log('✅  config.js generated successfully.');
